[mysql]
host = "localhost"
port = 3306
user = "team"
passwd = "team"
db = "gin"
timeout = "10s"

[server]
port = 8082
env = "development"
logFile = "../logs/logs"
logRotate = 7

[redis]
host = "localhost"
port = 6379
passwd = ""
db = 1